package com.mobile.bolt.Model;

/**
 * Created by Neeraj on 2/24/2016.
 * Model for Image table.
 * graded: 0 for not graded 1 for graded
 * uploaded: 0 for not uploaded 1 for uploaded.
 * question comments: comments written by the grader.
 * Grade: grade generated by the similarity mesure
 * GradeActual: grade as suggested by the grader.
 * Location: is the place where the image is stored on the file system.
 * Qrcode values stores the qr code values once the image once the image is graded. The values are stored as Forloop:8;Whileloop:6 in the database.
 */

public class Image {
    private int id;
    private String ASU_ID;
    private int graded;
    private int uploaded;
    private String QrCodeSolution;
    private String QuestionComments;
    private float Grade;
    private float GradeActual;
    private String Location;
    private String QrCodeValues; //shameless hack

    public float getGradeActual() {
        return GradeActual;
    }

    public void setGradeActual(float gradeActual) {
        GradeActual = gradeActual;
    }

    public float getGrade() {
        return Grade;
    }

    public void setGrade(float grade) {
        Grade = grade;
    }

    public String getQuestionComments() {
        return QuestionComments;
    }

    public void setQuestionComments(String questionComments) {
        QuestionComments = questionComments;
    }



    public String getQrCodeValues() {
        return QrCodeValues;
    }

    public void setQrCodeValues(String qrCodeValues) {
        QrCodeValues = qrCodeValues;
    }

    public Image(){
    }

    public String getQrCodeSolution() {
        return QrCodeSolution;
    }

    public void setQrCodeSolution(String qrCode) {
        QrCodeSolution = qrCode;
    }

    public int getGraded() {
        return graded;
    }

    public void setGraded(int graded) {
        this.graded = graded;
    }

    public int getUploaded() {
        return uploaded;
    }

    public void setUploaded(int uploaded) {
        this.uploaded = uploaded;
    }

    public void setId(int id) {
        this.id = id;
    }



    public int getId() {
        return id;
    }

    public String getASU_ID() {
        return ASU_ID;
    }

    public void setASU_ID(String ASU_ID) {
        this.ASU_ID = ASU_ID;
    }

    public String getLocation() {
        return Location;
    }

    public void setLocation(String location) {
        Location = location;
    }

    @Override
    public String toString(){
        return id+" "+ASU_ID+" "+Location+" "+graded+" "+uploaded+" "+QrCodeSolution+" "+QrCodeValues+" "+QuestionComments+" "+String.valueOf(Grade)+" "+String.valueOf(GradeActual);
    }
}
